services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: be-fkri
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    tty: true
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
